using UnityEngine;
using Unity.MLAgents;
using KartGame.AI;

/// <summary>
/// An example of how to use ML-Agents without inheriting from the Agent class.
/// Observations are generated by the attached SensorComponent, and the actions
/// are retrieved from the Agent.
/// </summary>
public class BasicController : MonoBehaviour
{
    KartAgent m_Agent;

    public void OnEnable()
    {
        m_Agent = GetComponent<KartAgent>();
    }

    public void FixedUpdate()
    {
        //if (!m_Agent.IsInTheAir()) {
            m_Agent?.RequestDecision();
        //} 
    }
}

